### PR TITLE
Fix handling of textDocument/foldingRange

### LINKED ISSUE #142: textDocument/foldingRange is not handled correctly
Folding ranges are controlled through the capability `textDocument/foldingRange`. This capability is currently not deserialized correctly at the server side. 

Given initialize params like this:

```
{
    // ...
    "capabilities": {
        // ...
        "textDocument": {
            // ...
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }        
    },
   // ..
}
```

The OnInitialize handle will get a capability model like this:

```
OmniSharp.Extensions.LanguageServer.Protocol.Supports`1[[OmniSharp.Extensions.LanguageServer.Protocol.Client.Capabilities.FoldingRangeCapability, OmniSharp.Extensions.LanguageProtocol, Version=0.0.9.9, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[xUnit.net 00:00:03.04]       {
[xUnit.net 00:00:03.04]          IsSupported = 
[xUnit.net 00:00:03.04]       False
[xUnit.net 00:00:03.04]          Value = <null>
[xUnit.net 00:00:03.04]          ValueType = 
[xUnit.net 00:00:03.04]       OmniSharp.Extensions.LanguageServer.Protocol.Client.Capabilities.FoldingRangeCapability
[xUnit.net 00:00:03.04]       }
```

### PR DESCRIPTION
**Pull request by fgreinacher**
Fixes #142

### CODE REVIEW

File: src/Protocol/Client/Capabilities/TextDocumentClientCapabilities.cs [hunk 1]
```diff
@@ -109,7 +109,7 @@ public class TextDocumentClientCapabilities
         ///
         /// Since 3.10.0
         /// </summary>
-        public Supports<FoldingRangeCapability> FoldingRangeProvider { get; set; }
+        public Supports<FoldingRangeCapability> FoldingRange { get; set; }
```
Comment (fgreinacher) [inline src/Protocol/Client/Capabilities/TextDocumentClientCapabilities.cs]: Please note that this is a breaking change. But as nobody complained that the capability is not working I assume very little people are using it :)

**Comment by fgreinacher** [comment]
@david-driscoll @mholo65 Happy to hear your feedback. Thanks in advance 😃

File: src/Protocol/Client/Capabilities/TextDocumentClientCapabilities.cs (hunk 1 above)
Comment (mholo65) [reply src/Protocol/Client/Capabilities/TextDocumentClientCapabilities.cs]: Nice catch! Yes, this breaking change is no problem as it didn’t even work in the first place 😄
